config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :moves
  resources :types
  root 'home#index'
  resources :pokemons
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.has_role?(:admin)
      can :manage, Pokemon
    else
      can :read, Pokemon
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/move.rb
class Move < ApplicationRecord
  belongs_to :type, optional: true
  has_many :pokemon_moves, dependent: :destroy
  has_many :pokemons, through: :pokemon_moves
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  belongs_to :type, optional: true
  has_many :pokemon_moves, dependent: :destroy
  has_many :moves, through: :pokemon_moves
end

app/models/pokemon_move.rb
class PokemonMove < ApplicationRecord
  belongs_to :pokemon
  belongs_to :move
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :pokemons
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :configure_permitted_parameters,
               if: :devise_controller?

    rescue_from CanCan::AccessDenied do |exception|
    	flash[:error] = exception.message
    	if request.env['HTTP_REFERER'].present?
    		redirect_to :back
    	else
    		redirect_to root_url
    	end
    end
 
 protected
 
 def configure_permitted_parameters
   added_attrs = %i( username )
   devise_parameter_sanitizer.permit(:sign_up, keys: added_attrs)
   devise_parameter_sanitizer.permit(:account_update, keys: added_attrs)
 end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/moves_controller.rb
class MovesController < ApplicationController
  before_action :set_move, only: [:show, :edit, :update, :destroy]

  # GET /moves
  # GET /moves.json
  def index
    @moves = Move.all
  end

  # GET /moves/1
  # GET /moves/1.json
  def show
  end

  # GET /moves/new
  def new
    @move = Move.new
  end

  # GET /moves/1/edit
  def edit
  end

  # POST /moves
  # POST /moves.json
  def create
    @move = Move.new(move_params)

    respond_to do |format|
      if @move.save
        format.html { redirect_to @move, notice: 'Attaque was successfully created.' }
        format.json { render :show, status: :created, location: @move }
      else
        format.html { render :new }
        format.json { render json: @move.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /moves/1
  # PATCH/PUT /moves/1.json
  def update
    respond_to do |format|
      if @move.update(move_params)
        format.html { redirect_to @move, notice: 'Attaque was successfully updated.' }
        format.json { render :show, status: :ok, location: @move }
      else
        format.html { render :edit }
        format.json { render json: @move.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /moves/1
  # DELETE /moves/1.json
  def destroy
    @move.destroy
    respond_to do |format|
      format.html { redirect_to moves_url, notice: 'Attaque was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_move
      @move = Move.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def move_params
      params.require(:move).permit(:name, :description, :type_id)
    end
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  before_action :set_pokemon, only: %i[show edit update destroy]
  before_action :authenticate_user!, only: %i[new edit create destroy update]
  authorize_resource

  def index
    @pokemons = Pokemon.includes(:type, moves: :type)
  end

  def edit; end

  def show; end

  # La var @pokemon est une variable uniquement accessible par la vue
  def new
    @pokemon = Pokemon.new
  end

  # permit sert à accepter certain champs d'un formulaire. Par défaut il accepte tout ce qui dangereux.
  def create
    @pokemon = Pokemon.new(pokemon_params)
    if @pokemon.save
      flash[:success] = "Le pokemon #{@pokemon.name} a bien été ajouté."
      redirect_to @pokemon
    else
      render 'new'
    end
  end

  def update
    @pokemon = Pokemon.find(params[:id])
    if @pokemon.update(pokemon_params)
      flash[:success] = "Le pokemon #{@pokemon.name} a bien été modifié."
      redirect_to @pokemon
    else
      render 'edit'
    end
  end

  def destroy
    @pokemon.destroy
    redirect_to pokemons_url
  end

  private

  def pokemon_params
    params.require(:pokemon).permit(:name, :number, :level, :health_points, :type_id, move_ids: [])
  end

  def set_pokemon
    @pokemon = Pokemon.find(params[:id])
  end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :set_type, only: %i[show edit update destroy]

  def index
    @types = Type.all
  end

  def show; end

  def new
    @type = Type.new
  end

  def edit; end

  def create
    @type = Type.new(type_params)
    if @type.save
      redirect_to @type, notice: 'Le type a bien été créé'
    else
      render :new
    end
  end

  # PATCH/PUT /types/1
  # PATCH/PUT /types/1.json
  def update
    if @type.update(type_params)
      redirect_to @type, notice: 'Le type a bien été mis à jour !'
    else
      render :edit
    end
  end

  # DELETE /types/1
  # DELETE /types/1.json
  def destroy
    @type.destroy
    redirect_to types_url, notice: 'Le type a bien été mis à jour !'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_type
    @type = Type.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def type_params
    params.require(:type).permit(:name, :color)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/moves_helper.rb
module MovesHelper
end

app/helpers/types_helper.rb
module TypesHelper
	def type_badge(name, color)
		raw "<span style='background-color: #{color}' class='badge'>
		#{name}
		</span>"
	end
end

app/views/home/index.html.erb
<h1>
  Ceci est la page d'acceuil du projet
  <%= Rails.application.class.parent.name %> !
</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pokedex</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
  <div class="container">
    <p>
      <%= link_to 'Pokemons', pokemons_path, class: 'btn btn-default' %>
      <%= link_to 'Types', types_path, class: 'btn btn-default' %>
      <%= link_to 'Attaques', moves_path, class: 'btn btn-default' %>

      <% if user_signed_in? %>
        Connecté en tant que <%= link_to current_user.username, edit_user_registration_path %> - <%= link_to 'Déconnexion', destroy_user_session_path, method: :delete, class: 'btn btn-danger' %>
      <% else %>
        <%= link_to 'connexion', new_user_session_path, class: 'btn btn-default' %>
      <% end %>
    </p>

    <% flash.each do | name, msg| %>
      <div class="alert alert-<%= name %>">
        <a class="close" data-dismiss="alert">x</a>
        <%= content_tag :div, msg, id: "flash_#{name}" %>      
      </div>
    <% end %>

    <br>
    <%= yield %>
  </div>
  </body>
</html>

app/views/moves/_form.html.erb
<%= simple_form_for(move) do |form| %>
  <div class="row">
    <div class="form-group col-lg-6">
      <%= form.input :name, label: 'Nom', class: 'form-control' %>
    </div>
    <div class="form-group col-lg-6">
      <%= form.input :description, label: 'Description', class: 'form-control' %>
    </div>
    <div class="form-group col-lg-6">
      <%= form.association :type, label: 'Type', class: 'form-control' %>
    </div>
  </div>

  <div class="field">
    <%= form.submit 'Enregistrer', class: 'btn btn-primary'%>
  </div>
<% end %>

app/views/moves/_moves_list.html.erb
<% if moves.any? %>
    <% moves.each do |m| %>
        <% if m.type.nil? %>
            <%= link_to m.name, m %>
                <% else %>
                    <%= link_to m do %>
					<%= type_badge(m.name, m.type.color) %>
                <% end %>
            <% end %>
        <% end %>
<% else %>
    &empty;
<% end %>

app/views/moves/edit.html.erb
<h1>Edition d'une attaque</h1>

<%= render 'form', move: @move %>

<%= link_to 'Show', @move %> |
<%= link_to 'Back', moves_path %>

app/views/moves/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<h1>Liste des attaques</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @moves.each do |move| %>
      <tr>
        <td><%= move.name %></td>
        <td><%= move.description %></td>
        <td>
          <% if move.type.nil? %>
          &empty;
          <% else %>
          <%= type_badge move.type.name, move.type.color %>
          <% end %>
            
        </td>
        <td><%= link_to 'Afficher', move, class: 'btn btn-info' %></td>
        <td><%= link_to 'Modifier', edit_move_path(move), class: 'btn btn-warning' %></td>
        <td><%= link_to 'Supprimer', move, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Ajouter une attaque', new_move_path, class: 'btn btn-success' %>

app/views/moves/new.html.erb
<h1>New Move</h1>

<%= render 'form', move: @move %>

<%= link_to 'Back', moves_path %>

app/views/moves/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<h2>Affichage d'une attaque</h2>

<p>
  <strong>Name:</strong>
  <%= @move.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @move.description %>
</p>

<p>
  <strong>Type:</strong>
  <% if @move.type.nil? %>
  Non défini
  <% else %>
  <%= type_badge @move.type.name, @move.type.color %>
  <% end %>
</p>

<%= link_to 'Modifier', edit_move_path(@move), class: 'btn btn-warning' %> |
<%= link_to 'Retour', moves_path, class: 'btn btn-default' %>

app/views/pokemons/_form.html.erb
<%= simple_form_for(pokemon) do |form| %>
  <div class="row">
    <div class="form-group col-lg-6">
      <%= form.input :name, label: 'Nom', class: 'form-control' %>
    </div>
    <div class="form-group col-lg-6">
      <%= form.input :number, label: 'Numéro', class: 'form-control' %>
    </div>
    <div class="form-group col-lg-6">
      <%= form.input :level, label: 'Niveau', class: 'form-control' %>
    </div>
    <div class="form-group col-lg-6">
      <%= form.input :health_points, label: 'Vie', class: 'form-control' %>
    </div>

    <div class="form-group col-lg-6">
      <%= form.association :type, label: 'Type', class: 'form-control' %>
    </div>

    <div class="form-group col-lg-6">
      <%= form.association :moves, as: :check_boxes, label: 'Attaques', class: 'form-control' %>
    </div>

  </div>

  <div class="field">
    <%= form.submit 'Enregistrer', class: 'btn btn-primary'%>
  </div>
<% end %>

app/views/pokemons/edit.html.erb
<h1>Modifier un pokemon</h1>

<%= render 'form', pokemon: @pokemon %>
<br>
<p>
  <%= link_to 'Afficher', @pokemon, class: 'btn btn-info' %>
  <%= link_to 'Retour à la liste des pokemons', pokemons_path, class: 'btn btn-default' %>
</p>

app/views/pokemons/index.html.erb
<h1>Liste des Pokemons</h1>

<% if @pokemons.any? %>
  <table class="table">
    <thead>
    <tr>
      <th>Id</th>
      <th>Nom</th>
      <th>Type</th>
      <th>Attaques</th>
    </tr>
    </thead>
    <tbody>
    <% @pokemons.each do |pokemon| %>
      <tr>
        <td><%= pokemon.id %></td>
        <td><%= pokemon.name %></td>
        <td>
          <% if pokemon.type.nil? %>
          &empty;
          <% else %>
          <%= type_badge pokemon.type.name, pokemon.type.color %>
          <% end %>
        </td>

        <td>
          <%= render 'moves/moves_list', moves: pokemon.moves %>
        </td>

        <td>
          <% if user_signed_in? %>
            <%= link_to 'Afficher', pokemon, class: 'btn btn-info' %>
          <% end %>
        </td>
        <td>
          <% if can? :update, pokemon %>
            <%= link_to 'Modifier', edit_pokemon_path(pokemon), class: 'btn btn-warning' %>
          <% end %>
        </td>
        <td>
          <% if can? :destroy, pokemon %>
            <%= link_to 'Supprimer', pokemon, method: :delete,
                      data: {
                          confirm: 'Êtes-vous sûr(e) de vouloir supprimer ce Pokemon ?'
                      },
                      class: 'btn btn-danger' %>
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>

  <p>Vous n'avez pas attrapé de Pokemon :(</p>
<% end %>

<% if can? :create, Pokemon %>
<p>
  <%= link_to 'Ajouter un pokemon', new_pokemon_path, class: 'btn btn-success' %>
</p>
<% end %>

app/views/pokemons/new.html.erb
<h1>Ajout des pokemons</h1>

<%= render 'form', pokemon: @pokemon %>

<p>
  <%= link_to 'Retour à la liste des pokemons', pokemons_path, class: 'btn btn-default' %>
</p>

app/views/pokemons/show.html.erb
<h1>Afficher un pokemon</h1>

<p>Nom : <%= @pokemon.name %></p>
<p>Numéro : <%= @pokemon.number %></p>
<p>Niveau : <%= @pokemon.level %></p>
<p>Vie : <%= @pokemon.health_points %> PV</p>

<p>
  Type :
  <% type = @pokemon.type %>
  <% if type.nil? %>
  non défini.
    <% else %>
  <!-- <span class="badge" style="background-color: <%= type.color %>"><%= type.name %></span> -->
 <%=  type_badge(type.name, type.color) %>
    <% end %>
</p>

<p>
	Attaques:
	<%= render 'moves/moves_list', moves: @pokemon.moves %>
</p>

<p>
  <%= link_to 'Modifier', edit_pokemon_path(@pokemon), class: 'btn btn-info' %>
  <%= link_to 'Retour à la liste des pokemons', pokemons_path, class: 'btn btn-default' %>
</p>

app/views/types/_form.html.erb
<%= form_with(model: type, local: true) do |form| %>
  <% if type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(type.errors.count, "error") %> empechant l'enregistrement :</h2>

      <ul>
      <% type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color %>
  </div>

  <div class="actions">
    <%= form.submit 'Enregistrer', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/types/edit.html.erb
<h1>Editing Type</h1>

<%= render 'form', type: @type %>
<br>
<%= link_to 'Afficher', @type, class: 'btn btn-info' %> |
<%= link_to 'Retour', types_path, class: 'btn btn-default' %>

app/views/types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Liste des types</h1>

<table class="table">
  <thead>
  <tr>
    <th>Name</th>
    <th>Color</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @types.each do |type| %>
    <tr>
      <td><%= type.name %></td>
      <td><%= type_badge type.color, type.color %></td>
      <td><%= link_to 'Afficher', type, class: 'btn btn-info' %></td>
      <td><%= link_to 'Modifier', edit_type_path(type), class: 'btn btn-warning' %></td>
      <td><%= link_to 'Supprimer', type, method: :delete, data: { confirm: 'Suppression !'}, class: 'btn btn-danger' %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Ajouter un Type', new_type_path, class: 'btn btn-success' %>

app/views/types/new.html.erb
<h1>New Type</h1>

<%= render 'form', type: @type %>

<%= link_to 'Back', types_path %>

app/views/types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @type.name %>
</p>

<p>
  <strong>Color:</strong>
  <%= type_badge @type.color, @type.color %>
</p>

<%= link_to 'Edit', edit_type_path(@type) %> |
<%= link_to 'Back', types_path %>